---

- name: ensure tasks run only on selected os releases
  block:

    - name: ensure tasks run only on selected os releases
      block:

        - name: enable CodeReady Linux Builder repository
          ansible.builtin.command:
            cmd: dnf config-manager --set-enabled crb

        - name: enable epel repositories
          ansible.builtin.package:
            name: "{{ item }}"
            state: present
          with_items:
            - epel-release
            - epel-next-release
      when: >
        ansible_distribution == "CentOS" or
        ansible_distribution == "Rocky"

    - name: ensure tasks run only on selected os releases
      block:

        - name: enable CodeReady Linux Builder repository
          ansible.builtin.command:
            cmd: subscription-manager repos --enable codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms

        - name: enable epel repositories
          ansible.builtin.package:
            name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
            state: present
            disable_gpg_check: true

      when: ansible_distribution == "RedHat"

  when: >
    ansible_distribution == "CentOS" or
    ansible_distribution == "RedHat" or
    ansible_distribution == "Rocky"

...
